### ISSUE TITLE
Maude

### ISSUE THREAD

**Issue by mpdehnel** [tamarin-prover/bin-dists#1]
If you don't have maude installed, it just sits and hangs. It throws the following error, but then sits and proceeds to max out all the machine's cores until you Ctrl+C it.

    maude tool: 'maude'
    checking version: caught exception while executing:
    maude --version
    with input:
    checking installation: caught exception while executing:
    maude
    with input: quit

This was on Ubuntu 14.04.3 LTS.
<img width="1217" alt="screenshot 2015-11-04 18 02 16" src="https://cloud.githubusercontent.com/assets/237223/10947708/6a4ce014-8321-11e5-8193-0d1f19a3607a.png">

**Comment by rsasse** [comment]
Thank you for the bug report. The issue has been fixed in the current development version just now. 

The tool will now abort at the point where maude is not available during test. Missing GraphViz will still continue. Note that the tool will not be able to work without Maude anyway.

**Comment by mpdehnel** [comment]
Great, thank you!
